### ISSUE TITLE
Improve the CI checks

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1800]
I think CI changes such as #1775 highlight a quite annoying problem: keeping the GitHub branch protection rules up to date.

There is different ways to deal with this, one which is to use a bot to keep in sync the rule protection based on what is declared in the workflow. However I'm not too fond of relying on external tooling for this, so I looked for another solution and managed to find one that I liked. The idea is very simple, instead of having a matrix generating:

```yaml
Test with PHP 7.4
Test with PHP 8.0
Test with PHP 8.1
Test with PHP 8.2
```

And manually adding each one of those jobs, you can simply use a "meta" job:

```yaml
    validate-tests:
        name: Tests status
        runs-on: ubuntu-latest
        needs: unit-tests
        if: always()
        steps:
            - name: Successful run
              if: ${{ !(contains(needs.*.result, 'failure')) }}
              run: exit 0

            - name: Failing run
              if: ${{ contains(needs.*.result, 'failure') }}
              run: exit 1
```

It will wait on all the job of the matrix, if all passed it will pass, otherwise it will fail. Then in the protection rule you can depend on this job only, which has a static name.

For an actual demo, you can check https://github.com/box-project/box/pull/812/checks where I've extensively reworked the CI to use this to the maximum (as I was quite sick of changing the protection rules...).

If you like the idea I'm happy to try to bring this to infection step by step.
