### ISSUE TITLE
Using PhpSpec as test framework does not seem to work

### ISSUE THREAD

**Issue by walterdolce** [infection/infection#246]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.1 (as defined in the `composer.json` file, for more info see #245)
| Test Framework version | PhpSpec 4.2.4
| PHP version | 7.1.4
| Platform    | macOS High Sierra 10.13.3
| Github Repo | ?

When running infection, it seems it's not detecting anything. As the documentation has currently little information about using it with PhpSpec, I am not sure whether this is expected or not.

```
$ bin/infection --test-framework=phpspec
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PhpSpec version: 4.2.4

    2 [============================] 3 secs

Generate mutants...

Processing source code files: 158/158
Creating mutated files and processes: 649/649
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   ( 50 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (100 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (150 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (200 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (250 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (300 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (350 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (400 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (450 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (500 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (550 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (600 / 649)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    (649 / 649)

649 mutations were generated:
       0 mutants were killed
     649 mutants were not covered by tests
       0 covered mutants were not detected
       0 errors were encountered
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 0%
         Mutation Code Coverage: 0%
         Covered Code MSI: 0%

Please note that some mutants will inevitably be harmless (i.e. false positives).
```

FYI, this is my project directory structure:
```
application/
   ...
   src/  <--- source files are here
   spec/ <--- PhpSpec spec files are here
   ...
composer.json
infection.json
phpspec.yml
...
```

My `infection.json` file is as follows:
```
{
    "timeout": 10,
    "source": {
        "directories": [
            "application/src/*"
        ],
        "exclude": [
            "application/vendor/*",
            "application/routes/*",
            "application/config/*",
            "application/features/*",
            "application/cache/*"
        ]
    },
    "phpUnit": {
        "configDir": ".",
        "customPath": "bin/phpunit"
    },
    "logs": {
        "text": "application/test-reports/mutation-testing/infection-log.txt",
        "summary": "application/test-reports/mutation-testing/summary-log.txt",
        "debug": "application/test-reports/mutation-testing/debug-log.txt"
    }
}
```

The `phpspec.yml` file is as follows instead:
```
extensions:
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - html
      - clover
      - xml
    output:
      html: application/test-reports/phpspec-coverage-html
      clover: application/test-reports/phpspec-coverage-clover/coverage.xml
      xml: application/test-reports/phpspec-coverage-xml
    blacklist:
      - application/vendor
    whitelist:
      - application/src
formatter.name: pretty
stop_on_failure: true
suites:
  default:
    spec_prefix: application\spec
    spec_path: %paths.config%
    src_path: %paths.config%/application/src
```
